name: grasp_analytics
dependencies:
  - numpy
  - matplotlib
  - pandas
  - scipy
  - pillow
  - pyyaml
  - pathlib
  - pytest
  - pyserial
  - conda-forge::pre_commit
  - plotly::plotly
  - boto3
  - botocore
  - tqdm
  - opencv
  - ultralytics
  - pip:
    - opencv-python
