{% set name = "grasp-analytics" %}
{% set version = "1.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_rev: "{{ version }}"
  git_url: "{{ https://gitlab.com/UBCBear/grasp-py.git }}"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - grasp_analytics

about:
  home: https://gitlab.com/UBCBear/grasp-py/
  license: BSD
  license_family: BSD
  summary: Analytics modules for GRASP
