grips: ['sea', 'pinch', 'ball', 'hammer', 'flat']
communication:
  UART:
    baud_rate: 115200
    port: '/dev/ttyACM0'
interaction:
  touchscreen: ~
  voice: ~
fsr_matrix:
  rows: 7
  columns: 11
  classifier:
    output_size: 4
  data:
    # Possible modes: uart, file
    # uart:
    #  Constant stream of data through communication_uart
    # File:
    #  Constant stream of data from the file until out of data in the file
    mode: "file"
    # Only needed if mode == "file", relative from "fsr_matrix/data_processing"
    file_path: "data/"
