from enum import Enum, auto


class GripType(Enum):
    CUP = auto(),
    PINCH = auto(),
    HAMMER = auto(),
    BALL = auto(),
    FIST = auto(),
    FLAT = auto()


obj_classes = {
    "bird": GripType.CUP,
    "cat": GripType.CUP,
    "dog": GripType.CUP,
    "hat": GripType.CUP,
    "backpack": GripType.CUP,
    "umbrella": GripType.CUP,
    "shoe": GripType.CUP,
    "eye glasses": GripType.CUP,
    "handbag": GripType.CUP,
    "tie": GripType.CUP,
    "suitcase": GripType.CUP,
    "frisbee": GripType.CUP,
    "skis": GripType.CUP,
    "snowboard": GripType.CUP,
    "sports ball": GripType.CUP,
    "kite": GripType.CUP,
    "baseball bat": GripType.CUP,
    "baseball glove": GripType.CUP,
    "skateboard": GripType.CUP,
    "surfboard": GripType.CUP,
    "tennis racket": GripType.CUP,
    "bottle": GripType.CUP,
    "plate": GripType.CUP,
    "wine glass": GripType.CUP,
    "cup": GripType.CUP,
    "fork": GripType.CUP,
    "knife": GripType.CUP,
    "spoon": GripType.CUP,
    "bowl": GripType.CUP,
    "banana": GripType.CUP,
    "apple": GripType.CUP,
    "sandwich": GripType.CUP,
    "orange": GripType.CUP,
    "broccoli": GripType.CUP,
    "carrot": GripType.CUP,
    "hot dog": GripType.CUP,
    "pizza": GripType.CUP,
    "donut": GripType.CUP,
    "cake": GripType.CUP,
    "chair": GripType.CUP,
    "couch": GripType.CUP,
    "potted plant": GripType.CUP,
    "bed": GripType.CUP,
    "mirror": GripType.CUP,
    "window": GripType.CUP,
    "door": GripType.BALL,
    "tv": GripType.CUP,
    "laptop": GripType.CUP,
    "mouse": GripType.CUP,
    "remote": GripType.CUP,
    "keyboard": GripType.CUP,
    "cell phone": GripType.CUP,
    "microwave": GripType.CUP,
    "oven": GripType.CUP,
    "toaster": GripType.CUP,
    "sink": GripType.CUP,
    "blender": GripType.CUP,
    "book": GripType.CUP,
    "clock": GripType.CUP,
    "vase": GripType.CUP,
    "scissors": GripType.CUP,
    "teddy bear": GripType.CUP,
    "hair drier": GripType.CUP,
    "toothbrush": GripType.CUP,
    "hair brush": GripType.CUP}
