from enum import Enum, auto


class GripType(Enum):
    TIP = auto(),
    LATERAL = auto(),
    TRIPOD = auto(),
    SPHERICAL = auto(),
    POWER = auto(),
    EXTENSION = auto()


obj_classes = {
    "bird": GripType.CUP,
    "cat": GripType.CUP,
    "dog": GripType.CUP,
    "hat": GripType.EXTENSION,
    "backpack": GripType.POWER,
    "umbrella": GripType.POWER,
    "shoe": GripType.PINCH,
    "eye glasses": GripType.CUP,
    "handbag": GripType.POWER,
    "tie": GripType.TIP,
    "suitcase": GripType.POWER,
    "frisbee": GripType.EXTENSION,
    "skis": GripType.EXTENSION,
    "snowboard": GripType.EXTENSION,
    "sports ball": GripType.SPHERICAL,
    "kite": GripType.EXTENSION,
    "baseball bat": GripType.POWER,
    "baseball glove": GripType.POWER,
    "skateboard": GripType.EXTENSION,
    "surfboard": GripType.EXTENSION,
    "tennis racket": GripType.POWER,
    "bottle": GripType.POWER,
    "plate": GripType.EXTENSION,
    "wine glass": GripType.POWER,
    "cup": GripType.POWER,
    "fork": GripType.TRIPOD,
    "knife": GripType.POWER,
    "spoon": GripType.TRIPOD,
    "bowl": GripType.EXTENSION,
    "banana": GripType.POWER,
    "apple": GripType.SPHERICAL,
    "sandwich": GripType.EXTENSION,
    "orange": GripType.SPHERICAL,
    "broccoli": GripType.POWER,
    "carrot": GripType.POWER,
    "hot dog": GripType.POWER,
    "pizza": GripType.LATERAL,
    "donut": GripType.POWER,
    "cake": GripType.POWER,
    "chair": GripType.POWER,
    "potted plant": GripType.CUP,
    "mirror": GripType.CUP,
    "window": GripType.CUP,
    "door": GripType.SPHERICAL,
    "laptop": GripType.EXTENSION,
    "mouse": GripType.SPHERICAL,
    "remote": GripType.LATERAL,
    "keyboard": GripType.CUP,
    "cell phone": GripType.CUP,
    "microwave": GripType.CUP,
    "toaster": GripType.CUP,
    "blender": GripType.CUP,
    "book": GripType.CUP,
    "clock": GripType.CUP,
    "vase": GripType.CUP,
    "scissors": GripType.CUP,
    "teddy bear": GripType.CUP,
    "hair drier": GripType.CUP,
    "toothbrush": GripType.CUP,
    "hair brush": GripType.CUP}
